### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by doronbehar** [DeXP/xkb-switch-win#1]

**Comment by DeXP** [comment]
Now it's one way only:
1. Download [Code Blocks](http://www.codeblocks.org/)
2. Open one of project files: `charmapgen.cbp` or `charmapgen.cbp`
3. Press "Build" button

**Comment by doronbehar** [comment]
O.K, I don't use windows at home but when I'll come back to work I'll check it, Thanks!
